### ISSUE TITLE
CTOになって半年の振り返りとこれから

### ISSUE THREAD

**Issue by konifar** [Kyash/recruitment#46]
## Overview

こんなこと書こうかなーという内容をざっと書いてください
リリース前の機能の情報などはここに書かないように注意してください

Kyash Techチームの構成やいいところ、取り組み、課題あたりを書いてほしいです！ by @konifar 

## Tasks

- [x] Slackでレビューを依頼した
- [x] 記事を公開してIssueにリンクをコメントした
- [x] (任意) [articles.md](https://github.com/Kyash/recruitment/blob/master/articles.md) にPull Requestを出した
- [ ] マイルストーンをクローズした

**Comment by ymzkmct** [comment]
published!
https://ymzkmct.hatenablog.com/entry/2021/06/30/125258
