### ISSUE TITLE
Visa決済基盤にProxyサーバーを導入したお話

### ISSUE THREAD

**Issue by konifar** [Kyash/recruitment#47]
## Overview

こんなこと書こうかなーという内容をざっと書いてください
リリース前の機能の情報などはここに書かないように注意してください

## Tasks

- [x] Slackでレビューを依頼した
- [x] 記事を公開してIssueにリンクをコメントした
- [x] (任意) [articles.md](https://github.com/Kyash/recruitment/blob/master/articles.md) にPull Requestを出した
- [x] マイルストーンをクローズした

**Comment by Sa2** [comment]
publish した記事のリンク
https://blog.kyash.co/entry/2021/07/02/080000
