### ISSUE TITLE
まじでゼロから始めるデータ分析と可視化

### ISSUE THREAD

**Issue by momota10** [Kyash/recruitment#61]
## Overview

こんなこと書こうかなーという内容をざっと書いてください
リリース前の機能の情報などはここに書かないように注意してください

## Tasks

- [x] Slackでレビューを依頼した
- [x] 記事を公開してIssueにリンクをコメントした
- [ ] (任意) [articles.md](https://github.com/Kyash/recruitment/blob/master/articles.md) にPull Requestを出した
- [x] マイルストーンをクローズした

**Comment by konifar** [comment]
社内Slackでのリクエストから

<img width="706" alt="20210812_105432_Slack | hr-blog | Kyash | 101 new items" src="https://user-images.githubusercontent.com/1269214/129126514-e4450574-3ef5-4377-a3ca-c1bc167d420a.png">

**Comment by konifar** [comment]
8/17 (火) はキツいので 8/19 (木) にリスケ

**Comment by piroyoung** [comment]
https://blog.kyash.co/entry/2021/08/18/163430
