### ISSUE TITLE
経理・会計をサポートするエンジニアチーム

### ISSUE THREAD

**Issue by aofox5152** [Kyash/recruitment#73]
## Overview

チームミッションとチーム紹介について書いてます。
※IPOについては、もちろん書かないようにしています。

## Tasks

- [x] Slackでレビューを依頼した
- [x] 記事を公開してIssueにリンクをコメントした
- [x] [articles.md](https://github.com/Kyash/recruitment/blob/master/articles.md) にPull Requestを出した
- [x] マイルストーンをクローズした

**Comment by aofox5152** [comment]
記事のURLは、こちらです！
https://foxtoy.hateblo.jp/entry/2021/07/19/100223

**Comment by konifar** [comment]
対応ありがとうございました！！
