### ISSUE TITLE
10%ルールの時間でTerraformをリファクタリングした話

### ISSUE THREAD

**Issue by yuu26jp** [Kyash/recruitment#89]
## Overview
自由に使える10%ルールの時間でTerraformをリファクタリングした

## Tasks
- [x] Slackでレビューを依頼した
- [x] 記事を公開してIssueにリンクをコメントした
- [x] (任意) [articles.md](https://github.com/Kyash/recruitment/blob/master/articles.md) にPull Requestを出した
- [ ] マイルストーンをクローズした

**Comment by konifar** [comment]
https://blog.yuu26.com/terraform-version-up/
